name: Auto-label new issues with "TRIAGE"

on:
  issues:
    types: [opened]

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add TRIAGE label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: TRIAGE
